// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Path = require("path");

var el = document.getElementById("myId");

var v = Path.join("a", "b", "aaa", "ccc");

x.onload = (function (v) {
    var o = this ;
    console.log(o.response + v | 0);
    
  });

exports.el = el;
exports.v = v;
/* el Not a pure module */
