// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var randnum = Math.random();

var rr = Math.round(5.222111);

console.log("random no :");

console.log(randnum);

console.log(rr);

var id = setTimeout((function (param) {
        console.log("hello");
        
      }), 1000);

clearTimeout(id);

var a = 5;

var b;

exports.a = a;
exports.b = b;
exports.randnum = randnum;
exports.rr = rr;
exports.id = id;
/* randnum Not a pure module */
