// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var name_obj = {
  info: {
    author: "Bob"
  }
};

var name = name_obj.info.author;

console.log("Hello, BuckleScript !!");

exports.name_obj = name_obj;
exports.name = name;
/* name Not a pure module */
