// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Caml_option = require("bs-platform/lib/js/caml_option.js");

var partial_arg = /* A */0;

function joe(param) {
  var tmp = {
    name: "Joe",
    age: 20
  };
  if (partial_arg !== undefined) {
    tmp.bg = Caml_option.valFromOption(partial_arg);
  }
  return tmp;
}

var pam = {
  name: "pam",
  age: 29
};

console.log(joe);

console.log(pam);

exports.joe = joe;
exports.pam = pam;
/*  Not a pure module */
