// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Caml_array = require("bs-platform/lib/js/caml_array.js");

var result = JSON.parse(" { \"names\": [\"Luke\", \"Christine\"] } ");

var name1 = Caml_array.caml_array_get(result.names, 0);

console.log(result);

console.log(name1);

exports.result = result;
exports.name1 = name1;
/* result Not a pure module */
